-- Sebil Tena schema (Turso / libSQL — also runs on local SQLite file).
-- The `pesticides` + `dosages` tables are the GROUND TRUTH for every
-- safety-critical field. Nothing here is ever generated by the LLM.
-- See SAFETY.md for the retriever-not-adviser boundary.

CREATE TABLE IF NOT EXISTS pesticides (
  id INTEGER PRIMARY KEY,
  registration_no TEXT UNIQUE NOT NULL,   -- the anchor identity for a product
  product_name TEXT NOT NULL,
  active_ingredient TEXT NOT NULL,
  formulation TEXT,
  registrant TEXT,
  registration_date TEXT,
  expiry_date TEXT,
  status TEXT CHECK(status IN ('registered','banned','suspended')) DEFAULT 'registered',
  hazard_class TEXT,          -- WHO acute hazard class (Ia, Ib, II, III, U)
  ppe_required TEXT,          -- JSON array of gear
  first_aid TEXT,             -- JSON: { route: [aid_code, ...] } — controlled vocab (src/aidCodes.js)
  approved_crops TEXT,        -- JSON array
  reviewed INTEGER DEFAULT 0, -- 1 only after toxicologist sign-off (SAFETY.md release gate)
  reviewed_by TEXT,           -- M10: reviewing professional's name (set on approve, cleared on revoke)
  reviewer_credential TEXT,   -- M10: their credential (e.g. "Clinical toxicologist, MD")
  reviewed_at TEXT,           -- M10: server timestamp of the current approval
  review_notes TEXT,          -- M10: reviewer's notes for the current approval
  created_at TEXT DEFAULT (datetime('now'))
);

-- Append-only review audit trail (M10). Every sign-off action (approve / revoke /
-- annotate) inserts a row here. This table is NEVER updated or deleted — it is
-- the auditable record handed to a regulator or attached to a grant application.
CREATE TABLE IF NOT EXISTS review_log (
  id INTEGER PRIMARY KEY,
  pesticide_id INTEGER REFERENCES pesticides(id),
  action TEXT CHECK(action IN ('approved','revoked','annotated')) NOT NULL,
  reviewer TEXT NOT NULL,     -- who performed the action
  credential TEXT,            -- their stated credential
  notes TEXT,                 -- approval notes, or the mandatory revoke reason
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS dosages (
  id INTEGER PRIMARY KEY,
  pesticide_id INTEGER REFERENCES pesticides(id),
  crop TEXT NOT NULL,
  dose_per_unit TEXT NOT NULL,       -- e.g. "2.5 ml per litre" — stored as retrieved fact
  application_notes TEXT,
  pre_harvest_interval_days INTEGER  -- PHI
);

CREATE TABLE IF NOT EXISTS scans (
  id INTEGER PRIMARY KEY,
  registration_no_read TEXT,
  matched_pesticide_id INTEGER,
  result_status TEXT,        -- VERIFIED / UNREGISTERED / EXPIRED / BANNED / SUSPENDED / UNCONFIRMED
  confidence TEXT,
  lat REAL, lon REAL,        -- geotag for surveillance map (with consent)
  region TEXT,
  language TEXT,
  channel TEXT,              -- app / sms
  resolved_status TEXT,      -- Tier-2 CONFIRM outcome: verify verdict, or REJECTED_BY_USER
  resolved_at TEXT,          -- when the CONFIRM was answered
  client_uuid TEXT,          -- client-generated id for idempotent offline sync (M6 Part C)
  synced_status TEXT,        -- authoritative online verdict recorded at sync time
  review_status TEXT,        -- M7.5 Part C: NULL=live, 'pending_review'=quarantined, 'released'=cleared by a human
  created_at TEXT DEFAULT (datetime('now'))
);
-- The UNIQUE index on client_uuid (idempotent sync) is created by the migration
-- in src/db.js so it runs AFTER the column exists on already-created tables.

-- SMS channel (M5): per-phone language preference + short-lived "last verified
-- product" session so `CROP <name>` and emergency-with-context work by text.
CREATE TABLE IF NOT EXISTS sms_users (
  phone TEXT PRIMARY KEY,
  lang TEXT,
  region TEXT,
  last_reg_no TEXT,
  last_pesticide_id INTEGER,
  last_active_ingredient TEXT,
  last_verified_at TEXT,          -- ISO; TTL-checked for CROP / emergency context
  created_at TEXT DEFAULT (datetime('now')),
  last_seen TEXT
);

-- Interaction telemetry (M5.6). Kept OUT of `scans` so it never corrupts the
-- safety-audit + surveillance counts (e.g. language fallbacks, help requests,
-- dose lookups, rate-limits). `scans` is verdicts only; telemetry lives here.
CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY,
  type TEXT NOT NULL,        -- lang_fallback / lang_set / lang_invalid / help / dose_lookup / rate_limited
  channel TEXT,              -- app / sms
  payload TEXT,              -- JSON (e.g. {"requested":"ti","chosen":"en"})
  region TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS extension_agents (
  id INTEGER PRIMARY KEY,
  name TEXT, phone TEXT, region TEXT
);

-- Shared-store rate limiter (M8 Part C). Fixed-window counters keyed by bucket
-- ("<prefix>:<key>"), so limits are enforced correctly across multiple Fly
-- machines (all point at the same Turso DB). Stale rows are swept periodically.
CREATE TABLE IF NOT EXISTS rate_limits (
  bucket TEXT PRIMARY KEY,
  window_start INTEGER NOT NULL,  -- epoch ms of the current window
  count INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pesticides_regno ON pesticides(registration_no);
CREATE INDEX IF NOT EXISTS idx_dosages_pesticide ON dosages(pesticide_id);
CREATE INDEX IF NOT EXISTS idx_scans_status ON scans(result_status);
