-- MedaGuard schema (Turso / libSQL — also runs on local SQLite file).
-- The `pesticides` + `dosages` tables are the GROUND TRUTH for every
-- safety-critical field. Nothing here is ever generated by the LLM.
-- See SAFETY.md for the retriever-not-adviser boundary.

CREATE TABLE IF NOT EXISTS pesticides (
  id INTEGER PRIMARY KEY,
  registration_no TEXT UNIQUE NOT NULL,   -- the anchor identity for a product
  product_name TEXT NOT NULL,
  active_ingredient TEXT NOT NULL,
  formulation TEXT,
  registrant TEXT,
  registration_date TEXT,
  expiry_date TEXT,
  status TEXT CHECK(status IN ('registered','banned','suspended')) DEFAULT 'registered',
  hazard_class TEXT,          -- WHO acute hazard class (Ia, Ib, II, III, U)
  ppe_required TEXT,          -- JSON array of gear
  first_aid TEXT,             -- JSON: {skin, eyes, ingestion, inhalation}
  approved_crops TEXT,        -- JSON array
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS dosages (
  id INTEGER PRIMARY KEY,
  pesticide_id INTEGER REFERENCES pesticides(id),
  crop TEXT NOT NULL,
  dose_per_unit TEXT NOT NULL,       -- e.g. "2.5 ml per litre" — stored as retrieved fact
  application_notes TEXT,
  pre_harvest_interval_days INTEGER  -- PHI
);

CREATE TABLE IF NOT EXISTS scans (
  id INTEGER PRIMARY KEY,
  registration_no_read TEXT,
  matched_pesticide_id INTEGER,
  result_status TEXT,        -- VERIFIED / UNREGISTERED / EXPIRED / BANNED / SUSPENDED / UNCONFIRMED
  confidence TEXT,
  lat REAL, lon REAL,        -- geotag for surveillance map (with consent)
  region TEXT,
  language TEXT,
  channel TEXT,              -- app / sms
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS extension_agents (
  id INTEGER PRIMARY KEY,
  name TEXT, phone TEXT, region TEXT
);

CREATE INDEX IF NOT EXISTS idx_pesticides_regno ON pesticides(registration_no);
CREATE INDEX IF NOT EXISTS idx_dosages_pesticide ON dosages(pesticide_id);
CREATE INDEX IF NOT EXISTS idx_scans_status ON scans(result_status);
